# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fbf43b1bef84bf0441844ccd305e13f4e8234afe6fbffd48e13d4d04d54fa774562336f7b6dcc285dc789641372617c3a49411fae1d2b1a253201490e4cb647

test:
  secret_key_base: d3d36a349fdeb21f085ce255c3107148fb23eeb002cce98d9512c0874a89d964c15841a7b7a155605729086456bd5a9ca71e17adb2bcce94c929f6be9216dcc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
